### ISSUE TITLE
I have a question. I have 2 forms of data: one is in .mat format with shape (rows, cols, bands) and the other is AVIRIS data I have downloaded from nasa.gov, both data have no labels and i want to perform anomaly detection on these these images. How do i do so?

### ISSUE THREAD

**Issue by Potafe** [Jingtao-Li-CVer/TDD#7]

**Comment by Potafe** [comment]
![Screenshot 2024-06-25 190954](https://github.com/Jingtao-Li-CVer/TDD/assets/139246033/d8550fd4-30c7-4be7-9566-780b6b1f15cb)

The above is the folder for my AVIRIS data downloaded open-source. I don't have any prior info on this data and want to perform your TDD HAD on this? How to do so?

**Comment by Jingtao-Li-CVer** [comment]
Thanks for your interest.

We have added the function to infer without labels as in updated ReadMe.

We use gdal to read the data, and you need to support matlab files yourself in HSIDataset_Inferring_Only.py using scipy package.

**Comment by Potafe** [comment]
Thank you for your quick response 👍🏾 :)
