### ISSUE TITLE
Hello again. Wanted to ask you about how to optimize the performance of TDD on datasets with larger spatial dimensions like (600, 400) to (1200, 1000). Right now it is not able to perform upto mark for such large datasets

### ISSUE THREAD

**Issue by Potafe** [Jingtao-Li-CVer/TDD#8]

**Comment by Jingtao-Li-CVer** [comment]
Some tips may be helpful. 
1 You can re-train TDD using some larger spectral datasets to enhance the generalizability. In the paper, TDD is trained only on HYDICE to verify the feasibility.
2 Image pre-processing such as the normalization manner has an obvious impact.
