### ISSUE TITLE
Hello again! Sorry for the dumb question, we have a test_input_size in the config file. What does it mean/do?

### ISSUE THREAD

**Issue by Potafe** [Jingtao-Li-CVer/TDD#9]
![IMG-20240801-WA0000.jpg](https://github.com/user-attachments/assets/42cf47e0-58f3-4ea1-a0c4-c98dd6a2b802)

**Comment by Potafe** [comment]
Does it resize the spatial dimensions of the image, for example if I have data with shape (400,400,400) it will resize it to (224,224,400) ?

**Comment by Potafe** [comment]
What I am able to understand from your paper and this code, is that the test_input_size is the one which creates the patch from the total image and the masked patch which we crop out from our original patch is test_patch_size.

Am I getting it right?

**Comment by Jingtao-Li-CVer** [comment]
For example, the image size is (200,200,270), patch_size is 10, test_input_sizes is 224. It means we crop a patch with size (10,10,270) from original image, and then resize it to (224,224,270) for model input

**Comment by Potafe** [comment]
Thanks for the clarification
